apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: sup0310/capsvote:v1
        name: vote
        ports:
        - containerPort: 80
          name: vote

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
spec:
  type: ClusterIP
  ports:
  - name: "vote-service"
    port: 80
    targetPort: 80
  selector:
    app: vote
