# DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
spec:
  replicas: 2
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: sup0310/capsresult:v1
        name: result
        ports:
        - containerPort: 80
          name: result

---
# SERVICE
apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result
spec:
  type: NodePort
  ports:
  - name: "result-service"
    port: 81
    targetPort: 80
    nodePort: 31001
  selector:
    app: result
